# Generated by Django 4.0.4 on 2022-04-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('dateSent', models.DateField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('supplyLot', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('countOnHold', models.PositiveIntegerField(blank=True, null=True)),
                ('dateCreated', models.DateField(null=True)),
                ('expiredDate', models.DateField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SupplyInOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count_in_order', models.PositiveIntegerField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('supply_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='supplies.order')),
                ('supply_in_storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.place'),
        ),
    ]
