# Generated by Django 4.0.4 on 2022-08-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(blank=True, max_length=200)),
                ('addressName', models.CharField(blank=True, max_length=200)),
                ('city_ref_NP', models.CharField(blank=True, max_length=100)),
                ('address_ref_NP', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Місце доставки',
                'verbose_name_plural': 'Міста доставки для організацій',
            },
        ),
        migrations.CreateModel(
            name='GeneralDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Прилад (назва)',
                'verbose_name_plural': 'Прилади (назва)',
            },
        ),
        migrations.CreateModel(
            name='GeneralSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('SMN_code', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.category')),
            ],
            options={
                'verbose_name': 'Товар (назва)',
                'verbose_name_plural': 'Товари (назва)',
            },
        ),
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ref', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('settlementType', models.CharField(max_length=100, null=True)),
                ('cityID', models.CharField(max_length=100, null=True)),
                ('settlementTypeDescription', models.CharField(max_length=100, null=True)),
                ('areaDescription', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Нова Пошта - Місто',
                'verbose_name_plural': 'Нова Пошта - Міста',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('dateSent', models.DateField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('dateSent', models.DateField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Замовлення в корзині',
                'verbose_name_plural': 'Замовлення в корзині',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('organization_code', models.PositiveIntegerField(blank=True, null=True)),
                ('ref_NP', models.CharField(blank=True, max_length=100, null=True)),
                ('city_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.city')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Організація',
                'verbose_name_plural': 'Організації',
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('dateSent', models.DateField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place')),
                ('userCreated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Передзамовлення',
                'verbose_name_plural': 'Передзамовлення',
            },
        ),
        migrations.CreateModel(
            name='PreorderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('dateSent', models.DateField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place')),
                ('userCreated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'передЗамовлення в корзині',
                'verbose_name_plural': 'передЗамовлення в корзині',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('supplyLot', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('countOnHold', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('expiredDate', models.DateField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.category')),
                ('general_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general', to='supplies.generalsupply')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100, null=True)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('telNumber', models.CharField(default='38', max_length=12)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_NP', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_counterparty_NP', models.CharField(blank=True, max_length=100, null=True)),
                ('for_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='supplies.place')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.CreateModel(
            name='SupplyInPreorderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('general_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generalsupply')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply')),
                ('supply_for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.preorderincart')),
            ],
            options={
                'verbose_name': 'Товар в передзамовленні в корзині',
                'verbose_name_plural': 'Товари в передзамовленні в коризні',
            },
        ),
        migrations.CreateModel(
            name='SupplyInPreorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('generalSupply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.generalsupply')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply')),
                ('supply_for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.preorder')),
            ],
            options={
                'verbose_name': 'Товар в Передзамовленні',
                'verbose_name_plural': 'Товари в Передзамовленнях',
            },
        ),
        migrations.CreateModel(
            name='SupplyInOrderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('supply', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply')),
                ('supply_for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.orderincart')),
            ],
            options={
                'verbose_name': 'Товар в замовленні в корзині',
                'verbose_name_plural': 'Товари в замовленні в коризні',
            },
        ),
        migrations.CreateModel(
            name='SupplyInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('internalName', models.CharField(blank=True, max_length=50, null=True)),
                ('internalRef', models.CharField(blank=True, max_length=30, null=True)),
                ('generalSupply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inGeneralSupp', to='supplies.generalsupply')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inSupply', to='supplies.supply')),
                ('supply_for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.order')),
            ],
            options={
                'verbose_name': 'Товар в замовленні',
                'verbose_name_plural': 'Товари в замовленнях',
            },
        ),
        migrations.CreateModel(
            name='ServiceNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('for_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервісна замітка',
                'verbose_name_plural': 'Сервісні замітки',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='worker_NP',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.workers'),
        ),
        migrations.AddField(
            model_name='orderincart',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
        migrations.AddField(
            model_name='orderincart',
            name='userCreated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
        migrations.AddField(
            model_name='order',
            name='userCreated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('general_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generaldevice')),
                ('in_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.city')),
                ('in_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place')),
            ],
            options={
                'verbose_name': 'Прилад',
                'verbose_name_plural': 'Прилади',
            },
        ),
    ]
