# Generated by Django 4.0.4 on 2022-08-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='isAddedToNP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='organization_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
