# Generated by Django 4.0.4 on 2022-05-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Прилад (назва)',
                'verbose_name_plural': 'Прилади (назва)',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('general_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generaldevice')),
                ('in_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place')),
            ],
            options={
                'verbose_name': 'Прилад',
                'verbose_name_plural': 'Прилади',
            },
        ),
    ]
