# Generated by Django 4.0.4 on 2022-09-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='dateCreated',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='dateScan',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
