# Generated by Django 4.0.4 on 2022-08-27 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='deliveryPlace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.deliveryplace'),
        ),
    ]
