# Generated by Django 4.0.4 on 2022-04-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinorder',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SuppInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('general_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.generalsupply')),
                ('supply_for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.order')),
            ],
            options={
                'verbose_name': 'Товар в замовленні!!!',
                'verbose_name_plural': 'Товари в замовленнях!!!',
            },
        ),
    ]
