# Generated by Django 4.0.4 on 2022-04-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='countOnHold',
        ),
    ]
