# Generated by Django 4.0.4 on 2022-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registernpinfo',
            name='register_url',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
