# Generated by Django 4.0.4 on 2022-09-05 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_registernpinfo_register_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registernpinfo',
            name='for_orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), blank=True, null=True, size=None),
        ),
    ]
