# Generated by Django 4.0.4 on 2022-08-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_place_deliveryplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='deliveryPlace',
        ),
        migrations.AddField(
            model_name='deliveryplace',
            name='for_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_places', to='supplies.place'),
        ),
    ]
