# Generated by Django 4.0.4 on 2022-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_statusnpparselfromdoucmentid_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusnpparselfromdoucmentid',
            name='actualDeliveryDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='statusnpparselfromdoucmentid',
            name='recipientDateTime',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
