# Generated by Django 4.0.4 on 2022-08-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_place_isaddedtonp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='isAddedToNP',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_in_NP',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
