# Generated by Django 4.0.4 on 2022-04-27 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_supplyinorder_date_created_suppinorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppinorder',
            name='general_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.generalsupply'),
        ),
    ]
