# Generated by Django 4.0.4 on 2022-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_remove_supply_countonhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='countOnHold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
