# Generated by Django 4.0.4 on 2022-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_generaldevice_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='date_installed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
