# Generated by Django 4.0.4 on 2022-04-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_suppinorder_general_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyinorder',
            name='supply_for',
        ),
        migrations.RemoveField(
            model_name='supplyinorder',
            name='supply_in_storage',
        ),
        migrations.AddField(
            model_name='supplyinorder',
            name='general_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.generalsupply'),
        ),
        migrations.AddField(
            model_name='supplyinorder',
            name='supply_for_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.order'),
        ),
        migrations.AlterField(
            model_name='supplyinorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='SuppInOrder',
        ),
    ]
