# Generated by Django 4.0.4 on 2022-08-27 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_remove_place_deliveryplace_deliveryplace_for_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryplace',
            options={'verbose_name': 'Місце доставки', 'verbose_name_plural': 'Місця доставок для організацій'},
        ),
        migrations.AddField(
            model_name='place',
            name='address_NP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.deliveryplace', unique=True),
        ),
    ]
