# Generated by Django 4.0.4 on 2022-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supply_countonhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='firebase_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
