# Generated by Django 4.0.4 on 2022-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_device_date_installed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
