# Generated by Django 4.0.4 on 2022-09-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_statusnpparselfromdoucmentid_actualdeliverydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='actualDeliveryDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='announcedPrice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='cargoDescriptionString',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='counterpartyRecipientDescription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='dateCreated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='dateScan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='documentCost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='documentWeight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='factualWeight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='payerType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='phoneRecipient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='recipientAddress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='recipientDateTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='recipientFullNameEW',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='scheduledDeliveryDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='seatsAmount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='warehouseSender',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
