# Generated by Django 4.0.4 on 2022-08-31 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_place_isaddedtonp_alter_place_name_in_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusnpparselfromdoucmentid',
            name='for_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.order'),
        ),
    ]
