# Generated by Django 4.0.4 on 2022-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_registernpinfo_for_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='npdeliverycreateddetailinfo',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='npdeliverycreateddetailinfo',
            name='recipient_worker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
