# Generated by Django 4.0.4 on 2022-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_supply_firebase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='hexcolor',
            field=models.CharField(default='#7acf48', max_length=7),
        ),
    ]
