# Generated by Django 4.0.4 on 2022-08-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_alter_deliveryplace_options_place_address_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryplace',
            name='deliveryType',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
