# Generated by Django 4.0.4 on 2022-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_remove_supplyinorder_supply_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
