# Generated by Django 4.0.4 on 2022-09-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_alter_statusnpparselfromdoucmentid_actualdeliverydate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address_NP',
        ),
        migrations.RemoveField(
            model_name='place',
            name='worker_NP',
        ),
    ]
