# Generated by Django 4.0.4 on 2022-08-31 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_statusnpparselfromdoucmentid_for_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createparselmodel',
            name='payment_money_type',
            field=models.CharField(choices=[('Cash', 'Готівка'), ('NonCash', 'Безготівковий')], default='NonCash', max_length=12),
        ),
        migrations.CreateModel(
            name='SenderNPPlaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(blank=True, max_length=200)),
                ('addressName', models.CharField(blank=True, max_length=200)),
                ('city_ref_NP', models.CharField(blank=True, max_length=100)),
                ('address_ref_NP', models.CharField(blank=True, max_length=100)),
                ('deliveryType', models.CharField(blank=True, max_length=20)),
                ('for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_np_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Місце доставки',
                'verbose_name_plural': 'Місця доставок для організацій',
            },
        ),
    ]
