# Generated by Django 4.0.4 on 2022-05-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_rename_name_workers_worker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='worker_name',
            new_name='name',
        ),
    ]
