# Generated by Django 4.0.4 on 2022-09-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_remove_place_address_np_remove_place_worker_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address_NP',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.deliveryplace'),
        ),
        migrations.AddField(
            model_name='place',
            name='worker_NP',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.workers'),
        ),
    ]
