# Generated by Django 4.0.4 on 2022-08-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_deliveryplace_deliverytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateParselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_user_type', models.CharField(choices=[('Sender', 'Відправник'), ('Recipient', 'Отримувач')], default='Sender', max_length=12)),
                ('payment_money_type', models.CharField(choices=[('Cash', 'Готівка'), ('NonCash', 'Безготівковий')], default='Cash', max_length=12)),
                ('width', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('seatsAmount', models.PositiveIntegerField()),
                ('description', models.CharField(default='Товари медичного призначення', max_length=200)),
                ('cost', models.PositiveIntegerField(blank=True, default=300, null=True)),
                ('dateDelivery', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPDeliveryCreatedDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=50)),
                ('cost_on_site', models.PositiveIntegerField()),
                ('estimated_time_delivery', models.CharField(max_length=12)),
                ('for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.order')),
            ],
            options={
                'verbose_name': 'НП Інфо по накладним',
                'verbose_name_plural': 'НП Накладні',
            },
        ),
    ]
