# Generated by Django 4.0.4 on 2022-04-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_supply_hexcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='hexcolor',
        ),
    ]
