# Generated by Django 4.0.4 on 2022-08-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_alter_createparselmodel_payment_money_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryplace',
            options={'verbose_name': 'Місце доставки НП', 'verbose_name_plural': 'Місця доставок для організацій НП'},
        ),
        migrations.AlterModelOptions(
            name='sendernpplaceinfo',
            options={'verbose_name': 'Місце відправки НП', 'verbose_name_plural': 'Місця відправок НП'},
        ),
        migrations.AddField(
            model_name='createparselmodel',
            name='sender_np_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.sendernpplaceinfo'),
        ),
        migrations.AlterField(
            model_name='createparselmodel',
            name='payment_money_type',
            field=models.CharField(choices=[('NonCash', 'Безготівковий'), ('Cash', 'Готівка')], default='NonCash', max_length=12),
        ),
    ]
