# Generated by Django 4.0.4 on 2022-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_remove_supply_hexcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinorder',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
