# Generated by Django 4.0.4 on 2022-08-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_alter_deliveryplace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='np_last_choosed_delivery_place_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
