# Generated by Django 4.0.4 on 2022-04-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_alter_generalsupply_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyinorder',
            name='general_supply',
        ),
        migrations.AddField(
            model_name='supplyinorder',
            name='generalSupply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inGeneralSupp', to='supplies.generalsupply'),
        ),
    ]
