# Generated by Django 4.0.4 on 2022-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_place_address_np_place_worker_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplysavefromscanapimodel',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
