# Generated by Django 4.0.4 on 2022-05-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0007_remove_supplyinorder_general_supply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('dateSent', models.DateField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.place')),
                ('userCreated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення в корзині',
                'verbose_name_plural': 'Замовлення в корзині',
            },
        ),
        migrations.CreateModel(
            name='SupplyInOrderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('generalSupply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inGeneralSuppForCart', to='supplies.generalsupply')),
                ('supply_for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.orderincart')),
            ],
            options={
                'verbose_name': 'Товар в замовленні в корзині',
                'verbose_name_plural': 'Товари в замовленні в коризні',
            },
        ),
    ]
