# Generated by Django 4.0.4 on 2022-09-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_customuser_np_last_choosed_delivery_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createparselmodel',
            name='sender_np_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.sendernpplaceinfo'),
        ),
    ]
