# Generated by Django 4.0.4 on 2022-11-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_supplysavefromscanapimodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='preCountOnHold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
