# Generated by Django 4.0.4 on 2022-08-30 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0007_statusnpparselfromdoucmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryplace',
            name='for_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_places', to='supplies.place'),
        ),
        migrations.AlterField(
            model_name='npdeliverycreateddetailinfo',
            name='for_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userCreated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_NP',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.deliveryplace'),
        ),
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='worker_NP',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.workers'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='for_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='supplies.place'),
        ),
    ]
