# Generated by Django 4.0.4 on 2022-04-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_alter_supplyinorder_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('dateCreated', models.DateField(blank=True, null=True)),
                ('for_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.place')),
            ],
            options={
                'verbose_name': 'Сервисная заметка',
                'verbose_name_plural': 'Сервисные заметки',
            },
        ),
    ]
