# Generated by Django 4.0.4 on 2022-05-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_orderincart_supplyinorderincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinorderincart',
            name='count_in_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
