# Generated by Django 4.0.4 on 2022-08-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_alter_deliveryplace_for_place_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryPlace',
            new_name='Delivery_Place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address_NP',
        ),
        migrations.RemoveField(
            model_name='place',
            name='worker_NP',
        ),
    ]
