# Generated by Django 4.0.4 on 2022-04-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_servicenote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Організація', 'verbose_name_plural': 'Організації'},
        ),
        migrations.AlterModelOptions(
            name='servicenote',
            options={'verbose_name': 'Сервісна замітка', 'verbose_name_plural': 'Сервісні замітки'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='supplyinorder',
            options={'verbose_name': 'Товар в замовленні', 'verbose_name_plural': 'Товари в замовленнях'},
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telNumber', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('for_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.place')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
    ]
