# Generated by Django 4.0.4 on 2022-09-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_alter_place_city_alter_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='organization_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
