# Generated by Django 4.0.4 on 2022-08-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_rename_deliveryplace_delivery_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='organization_code',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
