# Generated by Django 4.0.4 on 2022-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_agreement_supplyinagreement_order_for_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='dateSent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
