# Generated by Django 4.0.4 on 2022-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='firebase_id',
        ),
        migrations.AlterField(
            model_name='supply',
            name='dateCreated',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
