# Generated by Django 4.0.4 on 2022-08-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_alter_place_organization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address_NP',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.delivery_place'),
        ),
        migrations.AddField(
            model_name='place',
            name='worker_NP',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.workers'),
        ),
    ]
