# Generated by Django 4.0.4 on 2023-01-10 16:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_agreement_datesent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registernpinfo',
            name='barcode_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='barcode_image'),
        ),
    ]
