# Generated by Django 4.0.4 on 2022-05-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_alter_supplyinorder_supply_for_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyinorderincart',
            name='generalSupply',
        ),
        migrations.AddField(
            model_name='supplyinorder',
            name='internalName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplyinorder',
            name='internalRef',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplyinorder',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inSupply', to='supplies.supply'),
        ),
        migrations.AddField(
            model_name='supplyinorderincart',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply'),
        ),
        migrations.AlterField(
            model_name='supplyinorder',
            name='supply_for_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.order'),
        ),
    ]
