# Generated by Django 4.0.4 on 2022-05-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_remove_supplyinorderincart_generalsupply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinorderincart',
            name='supply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply'),
        ),
    ]
