# Generated by Django 4.0.4 on 2022-06-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_preorderincart_supplyinpreorderincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinpreorder',
            name='supply_for_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.preorder'),
        ),
    ]
