# Generated by Django 4.0.4 on 2022-04-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_place_address_place_link_servicenote_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
