# Generated by Django 4.0.4 on 2023-01-10 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0012_remove_registernpinfo_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='registernpinfo',
            name='barcode',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='barcode'),
        ),
    ]
