# Generated by Django 4.0.4 on 2022-05-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0012_alter_supplyinorderincart_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinorder',
            name='supply_for_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.order'),
        ),
    ]
