# Generated by Django 4.0.4 on 2022-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0012_alter_place_address_alter_place_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
