# Generated by Django 4.0.4 on 2022-06-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0012_alter_supplyinpreorder_supply_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyinpreorderincart',
            name='general_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generalsupply'),
        ),
    ]
