# Generated by Django 4.0.4 on 2022-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_supplyinpreorderincart_general_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinpreorderincart',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
