# Generated by Django 4.0.4 on 2023-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_device_image_alter_registernpinfo_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernpinfo',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
