# Generated by Django 4.0.4 on 2022-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_alter_place_address_alter_place_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenote',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
