# Generated by Django 4.0.4 on 2022-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_alter_supplyinorder_supply_for_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
