# Generated by Django 4.0.4 on 2023-01-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0014_alter_registernpinfo_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registernpinfo',
            name='barcode_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
