# Generated by Django 4.0.4 on 2022-05-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0014_alter_supply_datecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='firebase_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
        migrations.AlterField(
            model_name='orderincart',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='for_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='countOnHold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='for_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
    ]
