# Generated by Django 4.0.4 on 2022-06-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0014_alter_supplyinpreorderincart_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinpreorderincart',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply'),
        ),
    ]
