# Generated by Django 4.0.4 on 2022-06-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0015_alter_supplyinpreorderincart_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='in_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.city'),
        ),
    ]
