# Generated by Django 4.0.4 on 2022-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0016_device_in_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsupply',
            name='SMN_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalsupply',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalsupply',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplyLot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='telNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
