# Generated by Django 4.0.4 on 2022-08-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0017_generalsupply_smn_code_alter_generalsupply_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ref', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('settlementType', models.CharField(max_length=100, null=True)),
                ('cityID', models.CharField(max_length=100, null=True)),
                ('settlementTypeDescription', models.CharField(max_length=100, null=True)),
                ('areaDescription', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Нова Пошта - Місто',
                'verbose_name_plural': 'Нова Пошта - Міста',
            },
        ),
    ]
