# Generated by Django 4.0.4 on 2023-01-12 15:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0018_alter_device_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsupply',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
