# Generated by Django 4.0.4 on 2022-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0018_npcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='organization_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
