# Generated by Django 4.0.4 on 2023-03-02 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0019_generalsupply_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isUserAbleToDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
