# Generated by Django 4.0.4 on 2022-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0019_place_organization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ref_NP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
