# Generated by Django 4.0.4 on 2022-08-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0020_place_ref_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='middleName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='secondName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
