# Generated by Django 4.0.4 on 2022-08-26 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0021_workers_middlename_workers_secondname'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='phoneNumber',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
