# Generated by Django 4.0.4 on 2023-03-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0021_remove_place_user_place_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isUserAbleToDelivery',
        ),
    ]
