# Generated by Django 4.0.4 on 2022-08-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0022_workers_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='workers',
            name='telNumber',
            field=models.CharField(max_length=12),
        ),
    ]
