# Generated by Django 4.0.4 on 2023-03-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0022_remove_customuser_isuserabletodelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_preorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_for_preorder', to='supplies.preorder'),
        ),
        migrations.AddField(
            model_name='supplyinpreorder',
            name='count_in_order_current',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyinpreorder',
            name='state_of_delivery',
            field=models.CharField(blank=True, choices=[('Awaiting', 'Очікується'), ('Partial', 'Частково поставлено'), ('Complete', 'Повністю поставлено')], max_length=20, null=True),
        ),
    ]
