# Generated by Django 4.0.4 on 2022-08-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0023_remove_workers_phonenumber_alter_workers_telnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
