# Generated by Django 4.0.4 on 2023-03-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0023_order_for_preorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinpreorder',
            name='state_of_delivery',
            field=models.CharField(choices=[('Awaiting', 'Очікується'), ('Partial', 'Частково поставлено'), ('Complete', 'Повністю поставлено')], default='Awaiting', max_length=20),
        ),
    ]
