# Generated by Django 4.0.4 on 2022-08-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0024_alter_workers_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='telNumber',
            field=models.CharField(default='38', max_length=12),
        ),
    ]
