# Generated by Django 4.0.4 on 2023-03-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0024_alter_supplyinpreorder_state_of_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyinpreorder',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='supplyinpreorder',
            name='date_expired',
        ),
        migrations.RemoveField(
            model_name='supplyinpreorder',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='supplyinpreorder',
            name='supply',
        ),
    ]
