# Generated by Django 4.0.4 on 2022-08-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0025_alter_workers_telnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='ref_NP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
