# Generated by Django 4.0.4 on 2023-03-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0025_remove_supplyinpreorder_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyinpreorder',
            name='count_in_order_current',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
