# Generated by Django 4.0.4 on 2023-03-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0026_alter_supplyinpreorder_count_in_order_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='state_of_delivery',
            field=models.CharField(choices=[('Awaiting', 'Очікується'), ('Partial', 'Частково поставлено'), ('Complete', 'Повністю поставлено')], default='Awaiting', max_length=20),
        ),
    ]
