# Generated by Django 4.0.4 on 2022-08-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0026_workers_ref_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='ref_counterparty_NP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='for_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='supplies.place'),
        ),
    ]
