# Generated by Django 4.0.4 on 2022-08-27 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0027_workers_ref_counterparty_np_alter_workers_for_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='worker_NP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.workers', unique=True),
        ),
    ]
