# Generated by Django 4.0.4 on 2023-03-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0027_preorder_state_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyinorder',
            name='supply_in_preorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supplyinpreorder'),
        ),
    ]
