# Generated by Django 4.0.4 on 2022-08-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0028_place_worker_np'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='worker_NP',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.workers'),
        ),
    ]
