# Generated by Django 4.0.4 on 2023-03-13 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0029_remove_place_user_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
