# Generated by Django 4.0.4 on 2023-03-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0030_alter_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='for_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.agreement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='for_preorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_for_preorder', to='supplies.preorder'),
        ),
    ]
