# Generated by Django 4.0.4 on 2023-03-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0031_alter_order_for_agreement_alter_order_for_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='npdeliverycreateddetailinfo',
            name='userCreated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
