# Generated by Django 4.0.4 on 2023-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0032_npdeliverycreateddetailinfo_usercreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='organization_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
