# Generated by Django 4.0.4 on 2023-04-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0033_alter_place_organization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, to='supplies.category'),
        ),
        migrations.AddField(
            model_name='place',
            name='isPrivatePlace',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
