# Generated by Django 4.0.4 on 2023-04-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0034_place_allowed_categories_place_isprivateplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPrivatePlace',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
