# Generated by Django 4.0.4 on 2023-04-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0035_order_isprivateplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isPrivatePlace',
        ),
    ]
