# Generated by Django 4.0.4 on 2023-04-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0036_remove_order_isprivateplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='isPreorder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
