# Generated by Django 4.0.4 on 2023-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0037_preorder_ispreorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='state_of_delivery',
            field=models.CharField(choices=[('awaiting_from_customer', 'Формується замовником'), ('accepted_by_customer', 'Підтверджено замовником'), ('Awaiting', 'Замовлено у виробника'), ('Partial', 'Частково поставлено'), ('Complete', 'Повністю поставлено')], default='awaiting_from_customer', max_length=50),
        ),
    ]
