# Generated by Django 4.0.4 on 2023-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0038_alter_preorder_state_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateToSend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='dateToOrdered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
