# Generated by Django 4.0.4 on 2023-06-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0039_order_datetosend_preorder_datetoordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='SupplyForHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('history_description', models.CharField(blank=True, max_length=500, null=True)),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('supplyLot', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('countOnHold', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('expiredDate', models.DateField(null=True)),
                ('action_type', models.CharField(blank=True, choices=[('added', 'Додано'), ('deleted', 'Видалено'), ('updated', 'Оновлено')], max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.category')),
                ('general_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generalsupply')),
            ],
            options={
                'verbose_name': 'Товар (Історія)',
                'verbose_name_plural': 'Товари (Історія)',
            },
        ),
    ]
