# Generated by Django 4.0.4 on 2023-07-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0040_preorder_isclosed_alter_supply_name_supplyforhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyforhistory',
            name='supply_for_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.order'),
        ),
        migrations.AlterField(
            model_name='supplyforhistory',
            name='action_type',
            field=models.CharField(blank=True, choices=[('added-handle', 'Додано(Вручну)'), ('added-scan', 'Додано(Скан)'), ('added-order', 'Додано в замовлення'), ('deleted', 'Видалено'), ('updated', 'Оновлено')], max_length=100, null=True),
        ),
    ]
