# Generated by Django 4.0.4 on 2023-07-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0041_supplyforhistory_supply_for_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyforhistory',
            name='countOnHold',
        ),
    ]
