# Generated by Django 4.0.4 on 2023-12-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0042_remove_supplyforhistory_countonhold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySupplyInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=300, null=True)),
                ('supplyLot', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('expiredDate', models.CharField(blank=True, max_length=50, null=True)),
                ('isRecognized', models.BooleanField(default=False)),
                ('general_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generalsupply')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply')),
            ],
        ),
    ]
