# Generated by Django 4.0.4 on 2023-12-04 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0042_remove_supplyforhistory_countonhold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySupplyInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=300, null=True)),
                ('SMN_code', models.CharField(blank=True, max_length=300, null=True)),
                ('supplyLot', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('expiredDate', models.CharField(blank=True, max_length=50, null=True)),
                ('isRecognized', models.BooleanField(default=False)),
                ('isHandleAdded', models.BooleanField(default=False)),
                ('delivery_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.deliveryorder')),
                ('general_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generalsupply')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supply')),
            ],
            options={
                'verbose_name': 'Додані товари з поставки',
                'verbose_name_plural': 'Додані товари з поставки',
            },
        ),
    ]
