# Generated by Django 4.0.4 on 2023-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0043_deliverysupplyincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysupplyincart',
            name='barcode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
