# Generated by Django 4.0.4 on 2023-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0043_deliveryorder_deliverysupplyincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='isHasBeenSaved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverysupplyincart',
            name='expiredDate_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverysupplyincart',
            name='expiredDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
