# Generated by Django 4.0.4 on 2023-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0043_deliverysupplyincart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverysupplyincart',
            options={'verbose_name': 'Додані товари з поставки', 'verbose_name_plural': 'Додані товари з поставки'},
        ),
        migrations.AddField(
            model_name='deliverysupplyincart',
            name='SMN_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
