# Generated by Django 4.0.4 on 2024-01-04 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0044_deliveryorder_ishasbeensaved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('isPreorder', models.BooleanField(blank=True, default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('state_of_delivery', models.CharField(choices=[('Awaiting', 'Створено'), ('Partial', 'Частково поставлено'), ('Complete', 'Повністю поставлено')], default='Awaiting', max_length=50)),
                ('for_preorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.preorder')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place')),
                ('userCreated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
            },
        ),
        migrations.AlterField(
            model_name='supplyinorder',
            name='internalName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplyinorder',
            name='internalRef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplyinorder',
            name='lot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SupplyInBookedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('internalName', models.CharField(blank=True, max_length=500, null=True)),
                ('internalRef', models.CharField(blank=True, max_length=100, null=True)),
                ('generalSupply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.generalsupply')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.supply')),
                ('supply_in_booked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.bookedorder')),
            ],
            options={
                'verbose_name': 'Товар в бронюванні',
                'verbose_name_plural': 'Товари в бронюванні',
            },
        ),
    ]
