# Generated by Django 4.0.4 on 2023-12-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0045_deliveryorder_deliverysupplyincart_delivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
