# Generated by Django 4.0.4 on 2024-01-11 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0045_alter_supplyinorder_internalname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedOrderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('dateSent', models.DateField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place')),
                ('userCreated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронювання в корзині',
                'verbose_name_plural': 'Бронювання в корзині',
            },
        ),
        migrations.AddField(
            model_name='supplyinbookedorder',
            name='countOnHold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='supplyinbookedorder',
            name='supply_for_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.place'),
        ),
        migrations.AddField(
            model_name='supplyinbookedorder',
            name='supply_in_preorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supplyinpreorder'),
        ),
        migrations.AddField(
            model_name='supplyinorder',
            name='supply_in_booked_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supplyinbookedorder'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='state_of_delivery',
            field=models.CharField(choices=[('awaiting_from_customer', 'Формується замовником'), ('accepted_by_customer', 'Підтверджено замовником'), ('Awaiting', 'Замовлено у виробника'), ('Partial', 'Частково поставлено'), ('Complete', 'Повністю поставлено'), ('Complete_Handle', 'Повністю поставлено(Закрито вручну)')], default='awaiting_from_customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplyinbookedorder',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='BookedSupplyInOrderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expired', models.DateField(null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('supply', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.supplyinbookedorder')),
                ('supply_for_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.bookedorderincart')),
            ],
            options={
                'verbose_name': 'Товар в Бронюванні в корзині',
                'verbose_name_plural': 'Товари в Бронюванні в коризні',
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_teams_msg', models.BooleanField(default=True)),
                ('userCreated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
