# Generated by Django 4.0.4 on 2023-12-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0046_alter_deliveryorder_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
