# Generated by Django 4.0.4 on 2024-01-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0046_bookedorderincart_supplyinbookedorder_countonhold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsupplyinorderincart',
            name='supply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.supplyinbookedorder'),
        ),
    ]
