# Generated by Django 4.0.4 on 2024-02-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0047_alter_bookedsupplyinorderincart_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='enable_show_other_booked_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='send_teams_msg_preorders',
            field=models.BooleanField(default=True),
        ),
    ]
