# Generated by Django 4.0.4 on 2023-12-03 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0047_alter_deliveryorder_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
