# Generated by Django 4.2.4 on 2025-03-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0048_appsettings_enable_show_other_booked_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsupplyinorderincart',
            name='lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalsupply',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='statusnpparselfromdoucmentid',
            name='counterpartyRecipientDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplyinagreement',
            name='lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplyinorderincart',
            name='lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplyinpreorderincart',
            name='lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
