# Generated by Django 4.2.4 on 2025-03-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0050_order_usersent'),
    ]

    operations = [
        migrations.AddField(
            model_name='createparselmodel',
            name='cargo_type',
            field=models.CharField(choices=[('Parcel', 'Посилка'), ('Documents', 'Документи')], default='Parcel', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookedsupplyinorderincart',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyinbookedorder',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
