# Generated by Django 4.2.4 on 2025-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0051_createparselmodel_cargo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preorder',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
