# Generated by Django 4.2.4 on 2025-04-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0052_order_ispinned_preorder_ispinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyforhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplyforhistory',
            name='general_supply',
        ),
        migrations.RemoveField(
            model_name='supplyforhistory',
            name='supply_for_order',
        ),
        migrations.RemoveField(
            model_name='supplyinagreement',
            name='generalSupply',
        ),
        migrations.RemoveField(
            model_name='supplyinagreement',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='supplyinagreement',
            name='supply_for_agreement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='for_agreement',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='SupplyForHistory',
        ),
        migrations.DeleteModel(
            name='SupplyInAgreement',
        ),
    ]
