# Generated by Django 4.2.4 on 2025-04-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0053_remove_supplyforhistory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isMerged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='related_preorders',
            field=models.ManyToManyField(blank=True, related_name='related_orders', to='supplies.preorder'),
        ),
    ]
