# Generated by Django 4.2.4 on 2025-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0054_order_ismerged_order_related_preorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='disable_order_confirmation_send_action',
            field=models.BooleanField(default=False),
        ),
    ]
