# Generated by Django 4.2.4 on 2025-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0055_appsettings_disable_order_confirmation_send_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='enable_preorder_editing_awaiting_state',
            field=models.BooleanField(default=False),
        ),
    ]
