# Generated by Django 4.2.16 on 2026-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0057_telegrampendinglogin_telegramauthenticatedsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='home_show_edit_mode',
            field=models.BooleanField(default=True, verbose_name='Режим редагування (головна)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='home_show_order_cart',
            field=models.BooleanField(default=True, verbose_name='Кошик замовлення (головна)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='home_show_precart',
            field=models.BooleanField(default=True, verbose_name='Кошик передзамовлення (головна)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='home_show_smn',
            field=models.BooleanField(default=True, verbose_name='Показати SMN (головна)'),
        ),
    ]
