# Generated by Django 4.2.4 on 2026-06-05 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0059_customuser_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='send_teams_msg',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='send_teams_msg_preorders',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='push_new_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='push_new_orders_clients_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='push_new_preorders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='push_new_preorders_clients_only',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FcmDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('platform', models.CharField(default='android', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM пристрій',
                'verbose_name_plural': 'FCM пристрої',
            },
        ),
    ]
